### ISSUE TITLE
java.lang.NoClassDefFoundError: gnu/trove/map/TIntObjectMap under Forge 2729

### ISSUE THREAD

**Issue by Stormwind99** [Stormwind99/FoodFunk#17]
```
---- Minecraft Crash Report ----
// I just don't know what went wrong :(

Time: 2018-07-07 21:08:58 CST
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: gnu/trove/map/TIntObjectMap
at com.wumple.foodfunk.capability.ContainerListenerRot.createBulkUpdateMessage(ContainerListenerRot.java:38)
at com.wumple.foodfunk.capability.ContainerListenerRot.createBulkUpdateMessage(ContainerListenerRot.java:17)
at choonster.capability.CapabilityContainerListener.sendAllContents(CapabilityContainerListener.java:56)
at net.minecraft.inventory.Container.addListener(Container.java:52)
at choonster.capability.CapabilityContainerListenerManager$EventHandler.lambda$addListeners$0(CapabilityContainerListenerManager.java:57)
at java.lang.Iterable.forEach(Unknown Source)
at choonster.capability.CapabilityContainerListenerManager$EventHandler.addListeners(CapabilityContainerListenerManager.java:57)
at choonster.capability.CapabilityContainerListenerManager$EventHandler.playerLoggedIn(CapabilityContainerListenerManager.java:72)
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_14_EventHandler_playerLoggedIn_PlayerLoggedInEvent.invoke(.dynamic)
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
at net.minecraftforge.fml.common.FMLCommonHandler.firePlayerLoggedIn(FMLCommonHandler.java:574)
at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:218)
at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:256)
at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:72)
at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.update(NetworkDispatcher.java:205)
at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:285)
at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:180)
at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:790)
at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:252)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: gnu.trove.map.TIntObjectMap
at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
at java.lang.ClassLoader.loadClass(Unknown Source)
at java.lang.ClassLoader.loadClass(Unknown Source)
... 23 more
Caused by: java.lang.NullPointerException
at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
... 25 more

 

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Minecraft Version: 1.12.2
Operating System: Windows 10 (amd64) version 10.0
Java Version: 1.8.0_162, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 6843552864 bytes (6526 MB) / 7709130752 bytes (7352 MB) up to 8589934592 bytes (8192 MB)
JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx8192m
IntCache: cache: 0, tcache: 0, allocated: 4, tallocated: 105
FML: MCP 9.42 Powered by Forge 14.23.4.2729 Optifine OptiFine_1.12.2_HD_U_E1 61 mods loaded, 61 mods active
States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

| State | ID | Version | Source | Signature |
|:--------- |:------------------- |:----------------------- |:----------------------------------------------- |:---------------------------------------- |
| UCHIJAAAA | minecraft | 1.12.2 | minecraft.jar | None |
| UCHIJAAAA | mcp | 9.42 | minecraft.jar | None |
| UCHIJAAAA | FML | 8.0.99.99 | forge-1.12.2-14.23.4.2729.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
| UCHIJAAAA | forge | 14.23.4.2729 | forge-1.12.2-14.23.4.2729.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
| UCHIJAAAA | firstaidcore | 1.0.0 | minecraft.jar | None |
| UCHIJAAAA | applecore | 3.1.3 | [CORE]AppleCore-mc1.12.2-3.1.3.jar | None |
| UCHIJAAAA | extendedrenderer | v1.0 | [CORE]coroutil-1.12.1-1.2.11.jar | None |
| UCHIJAAAA | coroutil | 1.12.1-1.2.11 | [CORE]coroutil-1.12.1-1.2.11.jar | None |
| UCHIJAAAA | configmod | v1.0 | [CORE]coroutil-1.12.1-1.2.11.jar | None |
| UCHIJAAAA | kjlib | 1.0.2 | [CORE]kjlib-1.0.2.jar | None |
| UCHIJAAAA | reborncore | 3.9.2.319 | [CORE]RebornCore-1.12.2-3.9.2.319-universal.jar | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
| UCHIJAAAA | ambientsounds | 2.0.0 | AmbientSounds_v2.3_mc1.12.2.jar | None |
| UCHIJAAAA | jei | 4.11.0.204 | jei_1.12.2-4.11.0.204.jar | None |
| UCHIJAAAA | appleskin | 1.0.9 | AppleSkin-mc1.12-1.0.9.jar | None |
| UCHIJAAAA | badmobs | 1.0.25 | BadMobs-1.12.2-1.0.25.jar | d476d1b22b218a10d845928d1665d45fce301b27 |
| UCHIJAAAA | foodfunk | 2.1.1 | foodfunk-1.12.2-2.1.1.jar | None |
| UCHIJAAAA | biomesoplenty | 7.0.1.2394 | BiomesOPlenty-1.12.2-7.0.1.2394-universal.jar | None |
| UCHIJAAAA | blur | 1.0.4-14 | Blur-1.0.4-14.jar | None |
| UCHIJAAAA | dynamictrees | 1.12.2-0.7.8 | DynamicTrees-1.12.2-0.7.8.jar | None |
| UCHIJAAAA | dynamictreesbop | 1.12.2-1.2 | DynamicTreesBOP-1.12.2-1.2.jar | None |
| UCHIJAAAA | ftblib | 5.2.0.24 | FTBLib-5.2.0.24.jar | None |
| UCHIJAAAA | journeymap | 1.12.2-5.5.2 | journeymap-1.12.2-5.5.2.jar | None |
| UCHIJAAAA | ftbutilities | 5.2.0.29 | FTBUtilities-5.2.0.29.jar | None |
| UCHIJAAAA | cfm | 5.1.0 | furniture-5.1.0-1.12.2.jar | None |
| UCHIJAAAA | geolosys | 1.9.4 | Geolosys-1.12.2-1.9.4.jar | None |
| UCHIJAAAA | gravestone | 1.0.16 | GraveStone-1.12.2-Graves-1.0.16.jar | None |
| UCHIJAAAA | gravestone-extended | 1.3.0b7 | GraveStone-1.12.2-Extended-1.3.0b7.jar | None |
| UCHIJAAAA | hud | 1.3.9 | hud-1.3.9-1.12.jar | None |
| UCHIJAAAA | waila | 1.8.26 | Hwyla-1.8.26-B41_1.12.2.jar | None |
| UCHIJAAAA | i18nmod | @VERSION | i18nupdatemod-1.12.2-1.0.1.jar | None |
| UCHIJAAAA | iguanatweaks | 1.3.9 | IguanaTweaksReborn-1.3.9-mc1.12.x.jar | None |
| UCHIJAAAA | harvestcraft | 1.12.2u | Pam's+HarvestCraft+1.12.2u.jar | None |
| UCHIJAAAA | jehc | 1.12.2 | JEHC-1.12.2-1.6.0.0.jar | None |
| UCHIJAAAA | jeiintegration | 1.5.1.36 | jeiintegration_1.12.2-1.5.1.36.jar | None |
| UCHIJAAAA | jeivillagers | 1.0 | jeivillagers-1.12-1.0.2.jar | None |
| UCHIJAAAA | jepb | 1.2.1 | jepb-1.12-1.2.1.jar | None |
| UCHIJAAAA | jeresources | 0.8.6.28 | JustEnoughResources-1.12.2-0.8.6.28.jar | None |
| UCHIJAAAA | jeroreintegration | 1.1.0 | JEROreIntegration-1.12.2-1.1.0 (1).jar | None |
| UCHIJAAAA | lunatriuscore | 1.2.0.42 | LunatriusCore-1.12.2-1.2.0.42-universal.jar | None |
| UCHIJAAAA | mineralogy | 3.4.0 | Mineralogy-1.12-3.4.0.29.jar | d476d1b22b218a10d845928d1665d45fce301b27 |
| UCHIJAAAA | mousetweaks | 2.8 | MouseTweaks-2.8-mc1.12.1.jar | None |
| UCHIJAAAA | nutrition | 3.1.0 | Nutrition-1.12.2-3.1.0.jar | None |
| UCHIJAAAA | quickleafdecay | 1.2.4 | QuickLeafDecay-MC1.12.1-1.2.4.jar | None |
| UCHIJAAAA | spiceoflife | 1.3.12 | SpiceOfLife-mc1.12-1.3.12.jar | None |
| UCHIJAAAA | toughasnails | 3.1.0.124 | ToughAsNails-1.12.2-3.1.0.124-universal.jar | None |
| UCHIJAAAA | tanspit | 1.12.2-1.2 | tanspit-1.12.2-1.2.jar | None |
| UCHIJAAAA | teastory | 3.0.3.701 | TeaStory-3.0.3.701-1.12.2.jar | None |
| UCHIJAAAA | techreborn | 2.16.0.746 | TechReborn-1.12.2-2.16.0.746-universal.jar | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
| UCHIJAAAA | texfix | 4.0 | TexFix+V-1.12-4.0.jar | None |
| UCHIJAAAA | thirstybottles | 1.1.4 | ThirstyBottles-1.12.2-1.1.4.jar | d476d1b22b218a10d845928d1665d45fce301b27 |
| UCHIJAAAA | tiredness | 1.0.1 | Tiredness-1.0.1.jar | None |
| UCHIJAAAA | treechopper | 1.2.4 | TreeChopper-1.12.2-1.2.4.jar | None |
| UCHIJAAAA | vanillafix | 1.0.9-97 | VanillaFix-1.0.9-97.jar | None |
| UCHIJAAAA | wailaharvestability | 1.1.12 | WailaHarvestability-mc1.12-1.1.12.jar | None |
| UCHIJAAAA | waterstrainer | 3.2.0 | WaterStrainer-1.12-3.2.0.jar | None |
| UCHIJAAAA | wawla | 2.5.257 | Wawla-1.12.2-2.5.257.jar | d476d1b22b218a10d845928d1665d45fce301b27 |
| UCHIJAAAA | wearablebackpacks | 3.1.3 | WearableBackpacks-1.12.2-3.1.3.jar | None |
| UCHIJAAAA | worldedit | 6.1.8 | worldedit-forge-mc1.12-6.1.8-dist.jar | None |
| UCHIJAAAA | zombieawareness | 1.12.1-1.11.14 | zombieawareness-1.12.1-1.11.14.jar | None |
| UCHIJAAAA | firstaid | 1.5.6 | firstaid-1.5.6.jar | 7904c4e13947c8a616c5f39b26bdeba796500722 |
| UCHIJAAAA | hungeroverhaul | 1.12.2-1.3.3.jenkins148 | HungerOverhaul-1.12.2-1.3.3.jenkins148.jar | None |
Loaded coremods (and transformers): BlurPlugin (Blur-1.0.4-14.jar)
com.tterrag.blur.BlurTransformer
FirstAid CoreMod (firstaid-core-1.5.6.jar)
ichttt.mods.firstaid.common.asm.PotionTransformer
AppleCore ([CORE]AppleCore-mc1.12.2-3.1.3.jar)
squeek.applecore.asm.TransformerModuleHandler
VanillaFixLoadingPlugin (VanillaFix-1.0.9-97.jar)
GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
RebornCore: Plugin Engine: 0
RebornCore Version: 3.9.2.319
Runtime Debofucsation 1
RenderEngine: 1
Suspected Mods: Food Funk (foodfunk)
Profiler Position: N/A (disabled)
Player Count: 1 / 8; [EntityPlayerMP['SetSuna233'/2041, l='New World-', x=133.50, y=64.00, z=267.50]]
Type: Integrated Server (map_client.txt)
Is Modded: Definitely; Client brand changed to 'fml,forge'
```

**Comment by Stormwind99** [comment]
Forge devs report latest Forge removed trove library which Choonster's CapabiilityContainerListener used.
