### ISSUE TITLE
version 4.0.5+ startup crash please help

### ISSUE THREAD

**Issue by codydbgt** [Stormwind99/FoodFunk#35]
this is the stack trace for the crash i cant get heads or tails the cause. I think it could be a mod conflict 

Description: Initializing game

```
java.lang.NullPointerException: Initializing game
	at net.minecraft.client.util.SearchTree.func_194039_a(SourceFile:48)
	at java.util.ArrayList.forEach(Unknown Source)
	at net.minecraft.client.util.SearchTree.func_194042_b(SourceFile:48)
	at net.minecraft.client.util.SearchTree.func_194043_a(SourceFile:44)
	at java.util.ArrayList.forEach(Unknown Source)
	at net.minecraft.client.Minecraft.func_193986_ar(Minecraft.java:603)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:528)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```
 
[crash-2018-08-16_23.50.51-client.txt](https://github.com/Stormwind99/FoodFunk/files/2295958/crash-2018-08-16_23.50.51-client.txt)

**Comment by Stormwind99** [comment]
I don't see any evidence of which mod is causing the crash.  The stack trace is very odd and appears to be occurring during client initialization - before FoodFunk is even loaded.

Suggestions:
* I see you are running Forge 14.23.4.2732 - try the newer Forge 14.23.4.2757.
* Try disabling the mods one at a time, starting with the core mods listed at the beginning of the crash report.
* If using the Twitch launcher, use the "Repair Minecraft" option in the "..." menu of the profile.
