### ISSUE TITLE
Is there a way to fix this? My minecraft keeps crashing after I play for 5 mins.

### ISSUE THREAD

**Issue by OutLawBuster** [Stormwind99/FoodFunk#63]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.8-1.12.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.0.29.jar)
  weaponlib (mw-1.11.7.7_mc1.12.2.jar)
Contact their authors BEFORE contacting forge

// Hey, that tickles! Hehehe!

Time: 11/14/19 8:45 PM
Description: Exception ticking world

java.lang.IllegalArgumentException: Invalid null NBT value with key foodfunk:rot
	at net.minecraft.nbt.NBTTagCompound.func_74782_a(NBTTagCompound.java:85)
	at net.minecraftforge.common.capabilities.CapabilityDispatcher.serializeNBT(CapabilityDispatcher.java:123)
	at net.minecraft.item.ItemStack.func_77946_l(ItemStack.java:396)
	at net.minecraftforge.common.ForgeHooks$SeedEntry.getStack(ForgeHooks.java:184)
	at net.minecraftforge.common.ForgeHooks.getGrassSeed(ForgeHooks.java:201)
	at net.minecraft.block.BlockTallGrass.getDrops(BlockTallGrass.java:192)
	at net.minecraft.block.Block.getDrops(Block.java:1300)
	at net.minecraft.block.Block.func_180653_a(Block.java:571)
	at net.minecraft.block.Block.func_176226_b(Block.java:564)
	at net.minecraft.block.BlockBush.func_176475_e(BlockBush.java:67)
	at net.minecraft.block.BlockBush.func_180650_b(BlockBush.java:60)
	at net.minecraft.block.Block.func_180645_a(Block.java:508)
	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:476)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:225)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.nbt.NBTTagCompound.func_74782_a(NBTTagCompound.java:85)
	at net.minecraftforge.common.capabilities.CapabilityDispatcher.serializeNBT(CapabilityDispatcher.java:123)
	at net.minecraft.item.ItemStack.func_77946_l(ItemStack.java:396)
	at net.minecraftforge.common.ForgeHooks$SeedEntry.getStack(ForgeHooks.java:184)
	at net.minecraftforge.common.ForgeHooks.getGrassSeed(ForgeHooks.java:201)
	at net.minecraft.block.BlockTallGrass.getDrops(BlockTallGrass.java:192)
	at net.minecraft.block.Block.getDrops(Block.java:1300)
	at net.minecraft.block.Block.func_180653_a(Block.java:571)
	at net.minecraft.block.Block.func_176226_b(Block.java:564)
	at net.minecraft.block.BlockBush.func_176475_e(BlockBush.java:67)
	at net.minecraft.block.BlockBush.func_180650_b(BlockBush.java:60)
	at net.minecraft.block.Block.func_180645_a(Block.java:508)
	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:476)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:225)

-- Affected level --
Details:
	Level name: New World
	All players: 1 total; [EntityPlayerMP['OutLawBuster'/587, l='New World', x=138.51, y=64.75, z=-18.32]]
	Chunk stats: ServerChunkCache: 2027 Drop: 0
	Level seed: 2526588033388782566
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (184,64,256), Chunk: (at 8,4,0 in 11,16; contains blocks 176,0,256 to 191,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 9085 game time, 9085 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 86241 (now: false), thunder time: 112615 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 841719888 bytes (802 MB) / 3213885440 bytes (3065 MB) up to 3340763136 bytes (3186 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3584m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 Optifine OptiFine_1.12.2_HD_U_F4 76 mods loaded, 76 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                          | Version                  | Source                                        | Signature                                |
	|:------ |:--------------------------- |:------------------------ |:--------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft                   | 1.12.2                   | minecraft.jar                                 | None                                     |
	| LCHIJA | mcp                         | 9.42                     | minecraft.jar                                 | None                                     |
	| LCHIJA | FML                         | 8.0.99.99                | forge-1.12.2-14.23.5.2847.jar                 | None                                     |
	| LCHIJA | forge                       | 14.23.5.2847             | forge-1.12.2-14.23.5.2847.jar                 | None                                     |
	| LCHIJA | foamfixcore                 | 7.7.4                    | minecraft.jar                                 | None                                     |
	| LCHIJA | animalium                   | 0.3.8                    | Animalium-0.3.8.jar                           | None                                     |
	| LCHIJA | jei                         | 4.15.0.291               | jei_1.12.2-4.15.0.291.jar                     | None                                     |
	| LCHIJA | appleskin                   | 1.0.9                    | AppleSkin-mc1.12-1.0.9.jar                    | None                                     |
	| LCHIJA | ctm                         | MC1.12.2-1.0.0.29        | CTM-MC1.12.2-1.0.0.29.jar                     | None                                     |
	| LCHIJA | appliedenergistics2         | rv6-stable-7             | appliedenergistics2-rv6-stable-7.jar          | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| LCHIJA | baubles                     | 1.5.2                    | Baubles-1.12-1.5.2.jar                        | None                                     |
	| LCHIJA | mujmajnkraftsbettersurvival | 1.3.6                    | better_survival-1.3.6.jar                     | None                                     |
	| LCHIJA | betteradvancements          | 0.1.0.77                 | BetterAdvancements-1.12.2-0.1.0.77.jar        | None                                     |
	| LCHIJA | carryon                     | 1.12.3                   | CarryOn MC1.12.2 v1.12.3.jar                  | 55e88f24d04398481ae6f1ce76f65fd776f14227 |
	| LCHIJA | cavern                      | 2.2.0                    | Cavern_1.12.2-v2.2.0.jar                      | b78e30ad27c82f3e348f76edf497058678207299 |
	| LCHIJA | chameleon                   | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                      | None                                     |
	| LCHIJA | chancecubes                 | 1.12.2-4.1.0.300         | ChanceCubes-1.12.2-4.1.0.300.jar              | None                                     |
	| LCHIJA | codechickenlib              | 3.2.3.358                | CodeChickenLib-1.12.2-3.2.3.358-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | extendedrenderer            | v1.0                     | coroutil-1.12.1-1.2.32.jar                    | None                                     |
	| LCHIJA | coroutil                    | 1.12.1-1.2.32            | coroutil-1.12.1-1.2.32.jar                    | None                                     |
	| LCHIJA | configmod                   | v1.0                     | coroutil-1.12.1-1.2.32.jar                    | None                                     |
	| LCHIJA | craftablehorsearmour        | 1.3                      | CraftableHorseArmour-1.3.0-1.12.jar           | None                                     |
	| LCHIJA | crude_start                 | 1.0.0                    | CrudeStart-1.0.jar                            | None                                     |
	| LCHIJA | enchdesc                    | 1.1.15                   | EnchantmentDescriptions-1.12.2-1.1.15.jar     | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | enderstorage                | 2.4.6.137                | EnderStorage-1.12.2-2.4.6.137-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | enhancedvisuals             | 1.0                      | EnhancedVisuals_v1.2.7_mc1.12.2.jar           | None                                     |
	| LCHIJA | epicsiegemod                | 13.165                   | EpicSiegeMod-13.165.jar                       | None                                     |
	| LCHIJA | fastfood                    | 0.2.121859723            | FastFood-0.2.121859723.jar                    | None                                     |
	| LCHIJA | foamfix                     | 0.10.8-1.12.2            | foamfix-0.10.8-1.12.2.jar                     | None                                     |
	| LCHIJA | foodexpansion               | 1.3                      | FoodExpansion1.3.3-1.12.2.jar                 | None                                     |
	| LCHIJA | wumpleutil                  | 2.12.6                   | wumpleutil-1.12.2-2.12.6.jar                  | 1e57901a90acd4a3a54295b6decff5397be51a31 |
	| LCHIJA | foodfunk                    | 4.9.5                    | foodfunk-1.12.2-4.9.5.jar                     | 1e57901a90acd4a3a54295b6decff5397be51a31 |
	| LCHIJA | generaldisasters            | 1.0                      | generaldisasters-1.0.jar                      | None                                     |
	| LCHIJA | grapplemod                  | 1.12.2-v11.1             | grapplemod-v11.1-1.12.2.jar                   | None                                     |
	| LCHIJA | gravestone                  | 1.10.3                   | gravestone-1.10.3.jar                         | None                                     |
	| LCHIJA | ichunutil                   | 7.2.2                    | iChunUtil-1.12.2-7.2.2.jar                    | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | infernalcraft               | 1.12.2                   | InfernalCraft.jar                             | None                                     |
	| LCHIJA | ironbackpacks               | 1.12.2-3.0.8-12          | IronBackpacks-1.12.2-3.0.8-12.jar             | None                                     |
	| LCHIJA | ironchest                   | 1.12.2-7.0.67.844        | ironchest-1.12.2-7.0.72.847.jar               | None                                     |
	| LCHIJA | libraryex                   | 1.0.12                   | LibraryEx-1.12.2-1.0.12.jar                   | None                                     |
	| LCHIJA | thaumcraft                  | 6.1.BETA26               | Thaumcraft-1.12.2-6.1.BETA26.jar              | None                                     |
	| LCHIJA | lostmagic                   | 1.0                      | lostmagic-1.0.1.jar                           | None                                     |
	| LCHIJA | mantle                      | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55.jar                      | None                                     |
	| LCHIJA | mca                         | 6.1.0                    | MCA-1.12.2-6.1.0-universal.jar                | None                                     |
	| LCHIJA | twilightforest              | 3.10.1013                | twilightforest-1.12.2-3.10.1013-universal.jar | None                                     |
	| LCHIJA | tconstruct                  | 1.12.2-2.12.0.157        | TConstruct-1.12.2-2.12.0.157.jar              | None                                     |
	| LCHIJA | slabmachines                | 1.0.6                    | Slab_Machines-1.0.6.jar                       | None                                     |
	| LCHIJA | mcmultipart                 | 2.5.3                    | MCMultiPart-2.5.3.jar                         | None                                     |
	| LCHIJA | morecauldrons               | 1.4.6                    | More-Cauldrons-1.4.6.jar                      | None                                     |
	| LCHIJA | mousetweaks                 | 2.10                     | MouseTweaks-2.10-mc1.12.2.jar                 | None                                     |
	| LCHIJA | mutantmobs                  | 1.0.1                    | Mutant Mobs V1.0.1.jar                        | None                                     |
	| LCHIJA | mw                          | 1.11.7.7                 | mw-1.11.7.7_mc1.12.2.jar                      | None                                     |
	| LCHIJA | natura                      | 1.12.2-4.3.2.69          | natura-1.12.2-4.3.2.69.jar                    | None                                     |
	| LCHIJA | neat                        | 1.4-17                   | Neat 1.4-17.jar                               | None                                     |
	| LCHIJA | netherex                    | 2.0.15                   | NetherEx-1.12.2-2.0.15.jar                    | None                                     |
	| LCHIJA | oreexcavation               | 1.4.143                  | OreExcavation-1.4.143.jar                     | None                                     |
	| LCHIJA | orespawn                    | 3.3.1                    | OreSpawn-1.12-3.3.1.172.jar                   | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | getalltheseeds              | 1.12a                    | Pam's Get all the Seeds! 1.12a.jar            | None                                     |
	| LCHIJA | harvestcraft                | 1.12.2zb                 | Pam's HarvestCraft 1.12.2zf.jar               | None                                     |
	| LCHIJA | pamscookables               | 1.1                      | pamscookables-1.1.jar                         | None                                     |
	| LCHIJA | patchouli                   | 1.0-20                   | Patchouli-1.0-20.jar                          | None                                     |
	| LCHIJA | portalgun                   | 7.1.0                    | PortalGun-1.12.2-7.1.0.jar                    | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | progressivebosses           | 1.5.4                    | ProgressiveBosses-1.5.4-mc1.12.x.jar          | None                                     |
	| LCHIJA | punchmenot                  | 1.1                      | Punch Me Not 1.3-1.12.jar                     | None                                     |
	| LCHIJA | raiders                     | 3.0.9                    | raiders-1.12.2-3.0.9.jar                      | None                                     |
	| LCHIJA | stg                         | 1.12.2-1.2.3             | stg-1.12.2-1.2.3.jar                          | None                                     |
	| LCHIJA | stonechest                  | 1.0.4                    | StoneChest-1.0.4.jar                          | None                                     |
	| LCHIJA | storagedrawers              | 1.12.2-5.4.0             | StorageDrawers-1.12.2-5.4.0.jar               | None                                     |
	| LCHIJA | texfix                      | 4.0                      | TexFix-Mod-1.12.2.jar                         | None                                     |
	| LCHIJA | tinkertoolleveling          | 1.12.2-1.1.0.DEV.b23e769 | TinkerToolLeveling-1.12.2-1.1.0.jar           | None                                     |
	| LCHIJA | toughasnails                | 3.1.0.139                | ToughAsNails-1.12.2-3.1.0.139-universal.jar   | None                                     |
	| LCHIJA | trumpetskeleton             | 1.12-1.0.2.1             | trumpetskeleton-1.12-1.0.2.1.jar              | None                                     |
	| LCHIJA | walljump                    | 1.12.2-1.2.3             | walljump-1.12.2-1.2.3.jar                     | None                                     |
	| LCHIJA | weather2                    | 1.12.1-2.6.12            | weather2-1.12.1-2.6.12.jar                    | None                                     |
	| LCHIJA | wildcraft                   | 1.0                      | WildCraft-1.12.2- 1.0.1.0- F14.23.2.2611.jar  | None                                     |
	| LCHIJA | wolfarmor                   | 2.2.3.6                  | wolfarmor-1.12.2-2.2.3.1798-universal.jar     | None                                     |

	Loaded coremods (and transformers): 
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.8-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
CTMCorePlugin (CTM-MC1.12.2-1.0.0.29.jar)
  team.chisel.ctm.client.asm.CTMTransformer
weaponlib (mw-1.11.7.7_mc1.12.2.jar)
  com.vicmatskiv.weaponlib.core.WeaponlibClassTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	AE2 Version: stable rv6-stable-7 for Forge 14.23.5.2768
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaDecorative (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)

	AE2 Integration: IC2:OFF, RC:OFF, MFR:OFF, Waila:OFF, InvTweaks:OFF, JEI:ON, Mekanism:OFF, OpenComputers:OFF, THE_ONE_PROBE:OFF, TESLA:OFF, CRAFTTWEAKER:OFF
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['OutLawBuster'/587, l='New World', x=138.51, y=64.75, z=-18.32]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.2_HD_U_F4
	OptiFine Build: 20191023-234904
	Render Distance Chunks: 6
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 441.12
	OpenGlRenderer: GeForce GTX 1050 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by Stormwind99** [comment]
Possibly dupe of #56

**Comment by Stormwind99** [comment]
Food Funk 4.9.6 may have a workaround for this crash - can you try it out?
