### ISSUE TITLE
Tick ​​crash

### ISSUE THREAD

**Issue by Samlegamer** [Stormwind99/FoodFunk#82]
Hello I have been using food funk for some time and have noticed a crash that occurs randomly when I move away from my base which obviously contains a freezer.
Sometimes my backup crashes but I manage to reopen it easily (that's when the crash involves HashMap) but otherwise I have a second crash that occurs and which is almost never removed (HashMap $ HashIterator) and I can no longer reopen my backup.
I tried alternatives like debug mode or even daring debug but I have the impression that nothing prevents this bug: /

For info here is the version of the Mods:
- Forge 1.12.2-14.23.5.2854
- Food Funk - 1.12.2 - 4.9.6
- Wumple Utils - 1.12.2 - 2.12.9

I wonder if an earlier forge version would fix this bug 🤔

**Comment by Samlegamer** [comment]
Crash Report :
> Time: 2021-05-29 19:57:35 CEST
Description: Exception in server tick loop

java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
    at java.util.HashMap$ValueIterator.next(HashMap.java:1458)
    at net.minecraft.world.World.addTileEntities(World.java:1949)
    at net.minecraft.world.chunk.Chunk.onLoad(Chunk.java:856)
    at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:109)
    at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:150)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:728)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:279)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:745)

>

**Comment by MagmaSlime123** [comment]
Also having this.

**Comment by Samlegamer** [comment]
I managed to counteract the final crashes of the game with these mods:

Chunk-Pregenerator : https://www.curseforge.com/minecraft/mc-mods/chunkpregenerator
VanillaFix : https://www.curseforge.com/minecraft/mc-mods/vanillafix

Daring Debug can be a solution for the most desperate people.
https://www.curseforge.com/minecraft/mc-mods/daring-debug

When I say crashes, I mean only the definitive ones, you will crash sometimes at random.
Maybe also a mod that checks that the number of ticks is always stable at 3 by default could fix most crashes.
